# Generated by Django 5.1.2 on 2024-10-16 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_teste', models.DateField()),
                ('tipo_teste', models.CharField(choices=[('3k', '3 km'), ('12min', '12 minutos')], max_length=5)),
                ('tempo', models.TimeField(blank=True, null=True)),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bpm', models.IntegerField()),
                ('pace', models.CharField(blank=True, max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dr.aluno')),
            ],
        ),
    ]
