# Generated by Django 5.1.2 on 2024-10-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dr', '0003_alter_teste_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='tempo',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
